# Generated by Django 2.2.6 on 2019-10-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('authors', models.CharField(max_length=80)),
                ('publishedDate', models.CharField(max_length=80)),
                ('industryIdentifiers', models.CharField(max_length=80)),
                ('pageCount', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('imageLinks', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
