# Generated by Django 2.2.6 on 2019-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedDate',
            field=models.DecimalField(decimal_places=0, max_digits=100000),
        ),
    ]
