# Generated by Django 2.2.6 on 2019-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20191026_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
