# Generated by Django 2.2.6 on 2019-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20191026_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedDate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
