# Generated by Django 2.2.6 on 2019-10-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20191026_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedDate',
            field=models.CharField(max_length=10),
        ),
    ]
