# Generated by Django 2.2.6 on 2019-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20191026_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedDate',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
