# Generated by Django 2.2.6 on 2019-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_auto_20191026_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pageCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishedDate',
            field=models.IntegerField(default=0),
        ),
    ]
