# Generated by Django 2.2.6 on 2019-10-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_auto_20191026_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishedDate',
            field=models.CharField(default=1900, max_length=20),
        ),
    ]
