# Generated by Django 2.2.6 on 2019-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_auto_20191027_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='imageLinks',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='books',
            name='industryIdentifiers',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
